----Antes de nada introducir esto en la tabla Hechizos
---SELECT * FROM clases WHERE id = 1 al 6;
---INSERT INTO clases (id, nombre) VALUES (1, 'Artífice'); (2, Bardo)(3,Clerigo)(4,Druida)(5,GuardaBosque)(6,Paladin)

----->Artifice
INSERT INTO hechizos (clase_id, nombre, nivel, escuela, tiempo_casting, gama, duracion, componentes, enlace) VALUES
(1, 'Salpicaduras de ácido', 0, 'Conjuro', '1 Acción', '60 Pies', 'Instantáneo', 'V, S', 'hechizo_salpicaduras_acido.html'),
(1, 'Hoja retumbante', 0, 'Evocación', '1 Acción', 'Yo (radio de 5 pies)', '1 ronda', 'S, M', 'hechizo_hoja_retumbante.html'),
(1, 'Crear hoguera', 0, 'Conjuro', '1 Acción', '60 Pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_crear_hoguera.html'),
(1, 'Luces danzantes', 0, 'Evocación', '1 Acción', '120 Pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_luces_danzantes.html'),
(1, 'Proyectil de fuego', 0, 'Evocación', '1 Acción', '120 Pies', 'Instantáneo', 'V, S', 'hechizo_proyectil_fuego.html'),
(1, 'Escarcha mordiente', 0, 'Evocación', '1 Acción', '60 Pies', 'Instantáneo', 'V, S', 'hechizo_escarcha_mordiente.html'),
(1, 'Hoja de llama verde', 0, 'Evocación', '1 Acción', 'Yo (radio de 5 pies)', 'Instantáneo', 'S, M', 'hechizo_hoja_flama_verde.html'),
(1, 'Guía', 0, 'Adivinación', '1 Acción', 'Toque', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_guia.html'),
(1, 'Luz', 0, 'Evocación', '1 Acción', 'Toque', '1 hora', 'V, M', 'hechizo_luz.html'),
(1, 'Atracción de relámpago', 0, 'Evocación', '1 Acción', 'Yo (radio de 15 pies)', 'Instantáneo', 'V', 'hechizo_atraccion_relampago.html'),
(1, 'Mano de mago', 0, 'Conjuro', '1 Acción', '30 Pies', '1 minuto', 'V, S', 'hechizo_mano_mago.html'),
(1, 'Piedra mágica', 0, 'Transmutación', '1 Acción bonus', 'Toque', '1 minuto', 'V, S', 'hechizo_piedra_magica.html'),
(1, 'Remendar', 0, 'Transmutación', '1 Minuto', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_remendar.html'),
(1, 'Mensaje', 0, 'Transmutación', '1 Acción', '120 Pies', '1 ronda', 'V, S, M', 'hechizo_mensaje.html'),
(1, 'Rocío venenoso', 0, 'Conjuro', '1 Acción', '10 Pies', 'Instantáneo', 'V, S', 'hechizo_rocio_venenoso.html'),
(1, 'Prestidigitación', 0, 'Transmutación', '1 Acción', '10 Pies', 'Hasta 1 hora', 'V, S', 'hechizo_prestidigitacion.html'),
(1, 'Rayos de escarcha', 0, 'Evocación', '1 Acción', '60 Pies', 'Instantáneo', 'V, S', 'hechizo_rayos_escarcha.html'),
(1, 'Resistencia', 0, 'Abjuración', '1 Acción', 'Toque', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_resistencia.html'),
(1, 'Toque electrizante', 0, 'Evocación', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_toque_electrizante.html'),
(1, 'Preservar moribundo', 0, 'Nigromancia', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_preservar_moribundo.html'),
(1, 'Estallido de espadas', 0, 'Conjuro', '1 Acción', 'Yo (radio de 5 pies)', 'Instantáneo', 'V', 'hechizo_estallido_espadas.html'),
(1, 'Látigo de espinas', 0, 'Transmutación', '1 Acción', '30 Pies', 'Instantáneo', 'V, S, M', 'hechizo_latigo_espinas.html'),
(1, 'Estruendo de trueno', 0, 'Evocación', '1 Acción', 'Yo (radio de 5 pies)', 'Instantáneo', 'S', 'hechizo_estruendo_trueno.html'),
(1, 'Misil Mágico', 1, 'Evocación', '1 Acción', '120 Pies', 'Instantáneo', 'V, S', 'hechizo_misil_magico.html'),
(1, 'Escudo', 1, 'Abjuración', '1 Reacción', 'Personal', '1 ronda', 'V, S', 'hechizo_escudo.html'),
(1, 'Rayo de escarcha', 1, 'Evocación', '1 Acción', '60 Pies', 'Instantáneo', 'V, S', 'hechizo_rayo_escarcha.html'),
(1, 'Durabilidad de la piedra', 1, 'Abjuración', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_durabilidad_piedra.html'),
(1, 'Armadura de mago', 1, 'Abjuración', '1 Acción', 'Toque', '8 horas', 'V, S, M', 'hechizo_armadura_mago.html'),
(1, 'Detectar enemigos invisibles', 1, 'Conjuro', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_enemigos_invisibles.html'),
(1, 'Absorber elementos', 1, 'Abjuración', '1 Reacción', 'Personal', '1 ronda', 'S', 'hechizo_absorber_elementos.html'),
(1, 'Alarma', 1, 'Abjuración', '1 Minuto', '30 pies', '8 horas', 'V, S, M', 'hechizo_alarma.html'),
(1, 'Arma arcana (UA)', 1, 'Transmutación', '1 Acción bonus', 'Personal', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_arma_arcana.html'),
(1, 'Catapulta', 1, 'Transmutación', '1 Acción', '60 pies', 'Instantáneo', 'S', 'hechizo_catapulta.html'),
(1, 'Curar heridas', 1, 'Evocación', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_curar_heridas.html'),
(1, 'Detectar magia', 1, 'Adivinación', '1 Acción', 'Personal', 'Concentración, hasta 10 minutos', 'V, S', 'hechizo_detectar_magia.html'),
(1, 'Disfrazarse', 1, 'Ilusión', '1 Acción', 'Personal', '1 hora', 'V, S', 'hechizo_disfrazarse.html'),
(1, 'Retirada expeditiva', 1, 'Transmutación', '1 Acción bonus', 'Personal', 'Concentración, hasta 10 minutos', 'V, S', 'hechizo_retirada_expeditiva.html'),
(1, 'Fuego feérico', 1, 'Evocación', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V', 'hechizo_fuego_feerico.html'),
(1, 'Falsa vida', 1, 'Nigromancia', '1 Acción', 'Personal', '1 hora', 'V, S, M', 'hechizo_falsa_vida.html'),
(1, 'Caída de pluma', 1, 'Transmutación', '1 Reacción', '60 pies', '1 minuto', 'V, M', 'hechizo_caida_pluma.html'),
(1, 'Grasa', 1, 'Conjuro', '1 Acción', '60 pies', '1 minuto', 'V, S, M', 'hechizo_grasa.html'),
(1, 'Identificar', 1, 'Adivinación', '1 Minuto', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_identificar.html'),
(1, 'Salto', 1, 'Transmutación', '1 Acción', 'Toque', '1 minuto', 'V, S, M', 'hechizo_salto.html'),
(1, 'Zancada amplia', 1, 'Transmutación', '1 Acción', 'Toque', '1 hora', 'V, S, M', 'hechizo_zancada_amplia.html'),
(1, 'Purificar comida y bebida', 1, 'Transmutación', '1 Acción', '10 pies', 'Instantáneo', 'V, S', 'hechizo_purificar_comida.html'),
(1, 'Santuario', 1, 'Abjuración', '1 Acción bonus', '30 pies', '1 minuto', 'V, S, M', 'hechizo_santuario.html'),
(1, 'Trampa', 1, 'Abjuración', '1 Minuto', 'Toque', 'Hasta ser activada', 'V, S, M', 'hechizo_trampa.html'),
(1, 'Brebaje cáustico de Tasha', 1, 'Evocación', '1 Acción', 'Personal (línea de 30 pies)', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_brebaje_caustico.html'),
(1, 'Refuerzo', 2, 'Abjuración', '1 Acción', '30 Pies', '8 horas', 'V, S, M', 'hechizo_refuerzo.html'),
(1, 'Burbuja de aire', 2, 'Conjuro', '1 Acción', '60 Pies', '24 horas', 'S', 'hechizo_burbuja_aire.html'),
(1, 'Alterar apariencia', 2, 'Transmutación', '1 Acción', 'Personal', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_alterar_apariencia.html'),
(1, 'Candado arcano', 2, 'Abjuración', '1 Acción', 'Toque', 'Hasta ser disipado', 'V, S, M', 'hechizo_candado_arcano.html'),
(1, 'Imagen borrosa', 2, 'Ilusión', '1 Acción', 'Personal', 'Concentración, hasta 1 minuto', 'V', 'hechizo_imagen_borrosa.html'),
(1, 'Llama continua', 2, 'Evocación', '1 Acción', 'Toque', 'Hasta ser disipada', 'V, S, M', 'hechizo_llama_continua.html'),
(1, 'Visión en la oscuridad', 2, 'Transmutación', '1 Acción', 'Toque', '8 horas', 'V, S, M', 'hechizo_vision_oscuridad.html'),
(1, 'Potenciar habilidad', 2, 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_potenciar_habilidad.html'),
(1, 'Agrandar/reducir', 2, 'Transmutación', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_agrandar_reducir.html'),
(1, 'Calentar metal', 2, 'Transmutación', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_calentar_metal.html'),
(1, 'Invisibilidad', 2, 'Ilusión', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_invisibilidad.html'),
(1, 'Paseo cinético', 2, 'Transmutación', '1 Acción bonus', 'Personal', 'Concentración, hasta 1 minuto', 'S', 'hechizo_paseo_cinetico.html'),
(1, 'Restauración menor', 2, 'Abjuración', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_restauracion_menor.html'),
(1, 'Levitación', 2, 'Transmutación', '1 Acción', '60 pies', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_levitacion.html'),
(1, 'Boca mágica', 2, 'Ilusión', '1 Minuto', '30 pies', 'Hasta ser disipado', 'V, S, M', 'hechizo_boca_magica.html'),
(1, 'Arma mágica', 2, 'Transmutación', '1 Acción bonus', 'Toque', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_arma_magica.html'),
(1, 'Protección contra veneno', 2, 'Abjuración', '1 Acción', 'Toque', '1 hora', 'V, S', 'hechizo_proteccion_veneno.html'),
(1, 'Pirotécnia', 2, 'Transmutación', '1 Acción', '60 pies', 'Instantáneo', 'V, S', 'hechizo_pirotecnia.html'),
(1, 'Truco con la cuerda', 2, 'Transmutación', '1 Acción', 'Toque', '1 hora', 'V, S, M', 'hechizo_truco_cuerda.html'),
(1, 'Ver lo invisible', 2, 'Adivinación', '1 Acción', 'Personal', '1 hora', 'V, S, M', 'hechizo_ver_invisible.html'),
(1, 'Escribir en el cielo', 2, 'Transmutación', '1 Acción', 'Visual', 'Concentración, hasta 1 día', 'V, S', 'hechizo_escribir_cielo.html'),
(1, 'Trepar como araña', 2, 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_trepar_arana.html'),
(1, 'Vórtice de teletransporte', 2, 'Conjuro', '1 Acción', '90 pies', 'Instantáneo', 'V, S', 'hechizo_vortice_teletransporte.html'),
(1, 'Telaraña', 2, 'Conjuro', '1 Acción', '60 pies', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_telaraña.html'),
(1, 'Zancada de Ashardalon', 3, 'Transmutación', '1 Acción bonus', 'Personal', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_zancada_ashardalon.html'),
(1, 'Parpadear', 3, 'Transmutación', '1 Acción', 'Personal', '1 minuto', 'V, S', 'hechizo_parpadear.html'),
(1, 'Siesta felina', 3, 'Encantamiento', '1 Acción', '30 pies', '10 minutos', 'S, M', 'hechizo_siesta_felina.html'),
(1, 'Crear comida y agua', 3, 'Conjuro', '1 Acción', '30 pies', 'Instantáneo', 'V, S', 'hechizo_crear_comida_agua.html'),
(1, 'Disipar magia', 3, 'Abjuración', '1 Acción', '120 pies', 'Instantáneo', 'V, S', 'hechizo_disipar_magia.html'),
(1, 'Arma elemental', 3, 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_arma_elemental.html'),
(1, 'Flechas llameantes', 3, 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_flechas_llameantes.html'),
(1, 'Zancada de fuego (UA)', 3, 'Transmutación', '1 Acción bonus', 'Personal', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_zancada_fuego.html'),
(1, 'Volar', 3, 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_volar.html'),
(1, 'Glifo de protección', 3, 'Abjuración', '1 Hora', 'Toque', 'Hasta ser disipado o activado', 'V, S, M', 'hechizo_glifo_proteccion.html'),
(1, 'Prisa', 3, 'Transmutación', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_prisa.html'),
(1, 'Casa de naipes (UA)', 3, 'Conjuro', '1 Minuto', 'Toque', '24 horas', 'V, S, M', 'hechizo_casa_naipes.html'),
(1, 'Fortaleza mental', 3, 'Abjuración', '1 Acción', '30 pies', 'Concentración, hasta 1 hora', 'V', 'hechizo_fortaleza_mental.html'),
(1, 'Protección contra energía', 3, 'Abjuración', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_proteccion_energia.html'),
(1, 'Revivir', 3, 'Nigromancia', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_revivir.html'),
(1, 'Sirviente diminuto', 3, 'Transmutación', '1 Minuto', 'Toque', '8 horas', 'V, S', 'hechizo_sirviente_diminuto.html'),
(1, 'Respirar bajo el agua', 3, 'Transmutación', '1 Acción', '30 pies', '24 horas', 'V, S, M', 'hechizo_respirar_agua.html'),
(1, 'Caminar sobre el agua', 3, 'Transmutación', '1 Acción', '30 pies', '1 hora', 'V, S, M', 'hechizo_caminar_agua.html'),
(1, 'Ojo Arcano', 4, 'Adivinación', '1 Acción', '30 pies', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_ojo_arcano.html'),
(1, 'Perdición Elemental', 4, 'Transmutación', '1 Acción', '90 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_perdicion_elemental.html'),
(1, 'Fabricar', 4, 'Transmutación', '10 Minutos', '120 pies', 'Instantáneo', 'V, S', 'hechizo_fabricar.html'),
(1, 'Libertad de Movimiento', 4, 'Abjuración', '1 Acción', 'Toque', '1 hora', 'V, S, M', 'hechizo_libertad_movimiento.html'),
(1, 'Cofre Secreto de Leomund', 4, 'Conjuro', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_cofre_secreto.html'),
(1, 'Perro Fiel de Mordenkainen', 4, 'Conjuro', '1 Acción', '30 pies', '8 horas', 'V, S, M', 'hechizo_perro_fiel.html'),
(1, 'Santuario Privado de Mordenkainen', 4, 'Abjuración', '10 Minutos', '120 pies', '24 horas', 'V, S, M', 'hechizo_santuario_privado.html'),
(1, 'Esfera Resiliente de Otiluke', 4, 'Evocación', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_esfera_resiliente.html'),
(1, 'Formar Piedra', 4, 'Transmutación', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_formar_piedra.html'),
(1, 'Piel de Piedra', 4, 'Abjuración', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_piel_piedra.html'),
(1, 'Invocar Constructo', 4, 'Conjuro', '1 Acción', '90 pies', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_invocar_constructo.html'),
(1, 'Puño de hierro', 5, 'Evocación', '1 Acción', '60 pies', 'Instantáneo', 'V, S', 'hechizo_puño_iron.html'),
(1, 'Teletransportación menor', 5, 'Conjuro', '1 Acción', '30 pies', 'Instantáneo', 'V, S, M', 'hechizo_teletransportacion_menor.html'),
(1, 'Resurrección', 5, 'Necromancia', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_resurreccion.html'),
(1, 'Objetos animados', 5, 'Transmutación', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_objetos_animados.html'),
(1, 'Mano de Bigby', 5, 'Evocación', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_mano_bigby.html'),
(1, 'Crear timón de nave espacial', 5, 'Transmutación', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_crear_timon_nave_espacial.html'),
(1, 'Creación', 5, 'Ilusión', '1 Minuto', '30 pies', 'Especial', 'V, S, M', 'hechizo_creacion.html'),
(1, 'Restauración mayor', 5, 'Abjuración', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_restauracion_mayor.html'),
(1, 'Empoderamiento de habilidades', 5, 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_empoderamiento_habilidades.html'),
(1, 'Transmutar roca', 5, 'Transmutación', '1 Acción', '120 pies', 'Instantáneo', 'V, S, M', 'hechizo_transmutar_roca.html'),
(1, 'Muro de piedra', 5, 'Evocación', '1 Acción', '120 pies', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_muro_piedra.html');
----->Bardo
INSERT INTO hechizos (clase_id, nombre, nivel, tipo, escuela, tiempo_casting, gama, duracion, componentes, enlace) VALUES
(2, 'Protección de espada', 0, 'Cantrip', 'Abjuración', '1 Acción', 'Personal', '1 ronda', 'V, S', 'hechizo_proteccion_espada.html'),
(2, 'Luces danzantes', 0, 'Cantrip', 'Evocación', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_luces_danzantes.html'),
(2, 'Amigos', 0, 'Cantrip', 'Encantamiento', '1 Acción', 'Personal', 'Concentración, hasta 1 minuto', 'S, M', 'hechizo_amigos.html'),
(2, 'Luz', 0, 'Cantrip', 'Evocación', '1 Acción', 'Toque', '1 hora', 'V, M', 'hechizo_luz.html'),
(2, 'Mano de mago', 0, 'Cantrip', 'Conjuro', '1 Acción', '30 pies', '1 minuto', 'V, S', 'hechizo_mano_mago.html'),
(2, 'Remendar', 0, 'Cantrip', 'Transmutación', '1 Minuto', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_remendar.html'),
(2, 'Mensaje', 0, 'Cantrip', 'Transmutación', '1 Acción', '120 pies', '1 ronda', 'V, S, M', 'hechizo_mensaje.html'),
(2, 'Ilusión menor', 0, 'Cantrip', 'Ilusión', '1 Acción', '30 pies', '1 minuto', 'S, M', 'hechizo_ilusion_menor.html'),
(2, 'Prestidigitación', 0, 'Cantrip', 'Transmutación', '1 Acción', '10 pies', 'Hasta 1 hora', 'V, S', 'hechizo_prestidigitacion.html'),
(2, 'Estallido de trueno', 0, 'Cantrip', 'Evocación', '1 Acción', 'Personal (radio de 5 pies)', 'Instantáneo', 'S', 'hechizo_estallido_trueno.html'),
(2, 'Golpe certero', 0, 'Cantrip', 'Adivinación', '1 Acción', '30 pies', 'Concentración, hasta 1 ronda', 'S', 'hechizo_golpe_certero.html'),
(2, 'Burlas crueles', 0, 'Cantrip', 'Encantamiento', '1 Acción', '60 pies', 'Instantáneo', 'V', 'hechizo_burlas_crueles.html'),
(2, 'Amistad con animales', 1, '1Lvl', 'Encantamiento', '1 Acción', '30 pies', '24 horas', 'V, S, M', 'hechizo_amistad_animales.html'),
(2, 'Maldición', 1, '1Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_maldicion.html'),
(2, 'Hechizar persona', 1, '1Lvl', 'Encantamiento', '1 Acción', '30 pies', '1 hora', 'V, S', 'hechizo_hechizar_persona.html'),
(2, 'Rociada de color', 1, '1Lvl', 'Ilusión', '1 Acción', 'Personal (cono de 15 pies)', '1 ronda', 'V, S, M', 'hechizo_rociada_color.html'),
(2, 'Orden', 1, '1Lvl', 'Encantamiento', '1 Acción', '60 pies', '1 ronda', 'V', 'hechizo_orden.html'),
(2, 'Comprender idiomas', 1, '1Lvl', 'Adivinación', '1 Acción R', 'Personal', '1 hora', 'V, S, M', 'hechizo_comprender_idiomas.html'),
(2, 'Curar heridas', 1, '1Lvl', 'Evocación', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_curar_heridas.html'),
(2, 'Detectar magia', 1, '1Lvl', 'Adivinación', '1 Acción R', 'Personal', 'Concentración, hasta 10 minutos', 'V, S', 'hechizo_detectar_magia.html'),
(2, 'Disfrazarse', 1, '1Lvl', 'Ilusión', '1 Acción', 'Personal', '1 hora', 'V, S', 'hechizo_disfrazarse.html'),
(2, 'Susurros disonantes', 1, '1Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Instantáneo', 'V', 'hechizo_susurros_disonantes.html'),
(2, 'Distorsionar valor', 1, '1Lvl', 'Ilusión', '1 Minuto', 'Toque', '8 horas', 'V', 'hechizo_distorsionar_valor.html'),
(2, 'Temblor de tierra', 1, '1Lvl', 'Evocación', '1 Acción', 'Personal (radio de 10 pies)', 'Instantáneo', 'V, S', 'hechizo_temblor_tierra.html'),
(2, 'Fuego feérico', 1, '1Lvl', 'Evocación', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V', 'hechizo_fuego_feerico.html'),
(2, 'Caída de pluma', 1, '1Lvl', 'Transmutación', '1 Reacción', '60 pies', '1 minuto', 'V, M', 'hechizo_caida_pluma.html'),
(2, 'Mano guía (UA)', 1, '1Lvl', 'Adivinación', '1 Minuto R', '5 pies', 'Concentración, hasta 8 horas', 'V, S', 'hechizo_mano_guia.html'),
(2, 'Palabra curativa', 1, '1Lvl', 'Evocación', '1 Acción bonus', '60 pies', 'Instantáneo', 'V', 'hechizo_palabra_curativa.html'),
(2, 'Heroísmo', 1, '1Lvl', 'Encantamiento', '1 Acción', 'Toque', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_heroismo.html'),
(2, 'Identificar', 1, '1Lvl', 'Adivinación', '1 Minuto R', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_identificar.html'),
(2, 'Escritura ilusoria', 1, '1Lvl', 'Ilusión', '1 Minuto R', 'Toque', '10 días', 'S, M', 'hechizo_escritura_ilusoria.html'),
(2, 'Zancada larga', 1, '1Lvl', 'Transmutación', '1 Acción', 'Toque', '1 hora', 'V, S, M', 'hechizo_zancada_larga.html'),
(2, 'Marioneta (UA)', 1, '1Lvl', 'Encantamiento', '1 Acción', '120 pies', 'Instantáneo', 'V', 'hechizo_marioneta.html'),
(2, 'Sentir emoción (UA)', 1, '1Lvl', 'Adivinación', '1 Acción', 'Personal', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_sentir_emocion.html'),
(2, 'Imagen silenciosa', 1, '1Lvl', 'Ilusión', '1 Acción', '60 pies', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_imagen_silenciosa.html'),
(2, 'Púas plateadas', 1, '1Lvl', 'Encantamiento', '1 Reacción', '60 pies', 'Instantáneo', 'V', 'hechizo_púas_plateadas.html'),
(2, 'Dormir', 1, '1Lvl', 'Encantamiento', '1 Acción', '90 pies', '1 minuto', 'V, S, M', 'hechizo_dormir.html'),
(2, 'Hablar con animales', 1, '1Lvl', 'Adivinación', '1 Acción R', 'Personal', '10 minutos', 'V, S', 'hechizo_hablar_animales.html'),
(2, 'Despertar repentino (UA)', 1, '1Lvl', 'Encantamiento', '1 Acción bonus', '10 pies', 'Instantáneo', 'V', 'hechizo_despertar_repentino.html'),
(2, 'Risa horrible de Tasha', 1, '1Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_risa_tasha.html'),
(2, 'Onda de trueno', 1, '1Lvl', 'Evocación', '1 Acción', 'Personal (cubo de 15 pies)', 'Instantáneo', 'V, S', 'hechizo_onda_trueno.html'),
(2, 'Coro sobrenatural (UA)', 1, '1Lvl', 'Ilusión', '1 Acción', 'Personal (radio de 30 pies)', 'Concentración, hasta 10 minutos', 'V', 'hechizo_coro_sobrenatural.html'),
(2, 'Sirviente invisible', 1, '1Lvl', 'Conjuro', '1 Acción R', '60 pies', '1 hora', 'V, S, M', 'hechizo_sirviente_invisible.html'),
(2, 'Ayuda', 2, '2Lvl', 'Abjuración', '1 Acción', '30 pies', '8 horas', 'V, S, M', 'hechizo_ayuda.html'),
(2, 'Mensajero animal', 2, '2Lvl', 'Encantamiento', '1 Acción R', '30 pies', '24 horas', 'V, S, M', 'hechizo_mensajero_animal.html'),
(2, 'Ceguera/Sordera', 2, '2Lvl', 'Necromancia', '1 Acción', '30 pies', '1 minuto', 'V', 'hechizo_ceguera_sordera.html'),
(2, 'Conocimiento prestado', 2, '2Lvl', 'Adivinación', '1 Acción', 'Personal', '1 hora', 'V, S, M', 'hechizo_conocimiento_prestado.html'),
(2, 'Calmar emociones', 2, '2Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_calmar_emociones.html'),
(2, 'Nube de dagas', 2, '2Lvl', 'Conjuro', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_nube_dagas.html'),
(2, 'Corona de locura', 2, '2Lvl', 'Encantamiento', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_corona_locura.html'),
(2, 'Detectar pensamientos', 2, '2Lvl', 'Adivinación', '1 Acción', 'Personal', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_detectar_pensamientos.html'),
(2, 'Mejorar habilidad', 2, '2Lvl', 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_mejorar_habilidad.html'),
(2, 'Agrandar/Reducir', 2, '2Lvl', 'Transmutación', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_agrandar_reducir.html'),
(2, 'Cautivar', 2, '2Lvl', 'Encantamiento', '1 Acción', '60 pies', '1 minuto', 'V, S', 'hechizo_cautivar.html'),
(2, 'Don de palabra', 2, '2Lvl', 'Encantamiento', 'Reacción', 'Personal', 'Instantáneo', 'V, S, M', 'hechizo_don_palabra.html'),
(2, 'Calentar metal', 2, '2Lvl', 'Transmutación', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_calentar_metal.html'),
(2, 'Inmovilizar persona', 2, '2Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_inmovilizar_persona.html'),
(2, 'Invisibilidad', 2, '2Lvl', 'Ilusión', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_invisibilidad.html'),
(2, 'Paseo cinético', 2, '2Lvl', 'Transmutación', '1 Acción bonus', 'Personal', 'Concentración, hasta 1 minuto', 'S', 'hechizo_paseo_cinetico.html'),
(2, 'Golpear', 2, '2Lvl', 'Transmutación', '1 Acción', '60 pies', 'Instantáneo', 'V', 'hechizo_golpear.html'),
(2, 'Restauración menor', 2, '2Lvl', 'Abjuración', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_restauracion_menor.html'),
(2, 'Localizar animales o plantas', 2, '2Lvl', 'Adivinación', '1 Acción R', 'Personal', 'Instantáneo', 'V, S, M', 'hechizo_localizar_animales_plantas.html'),
(2, 'Localizar objeto', 2, '2Lvl', 'Adivinación', '1 Acción', 'Personal', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_localizar_objeto.html'),
(2, 'Boca mágica', 2, '2Lvl', 'Ilusión', '1 Minuto R', '30 pies', 'Hasta ser disipado', 'V, S, M', 'hechizo_boca_magica.html'),
(2, 'Imagen de espejo', 2, '2Lvl', 'Ilusión', '1 Acción', 'Personal', '1 minuto', 'V, S', 'hechizo_imagen_espejo.html'),
(2, 'Travesura de Nathair', 2, '2Lvl', 'Ilusión', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'S, M', 'hechizo_travesura_nathair.html'),
(2, 'Fuerza fantasmal', 2, '2Lvl', 'Ilusión', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_fuerza_fantasmal.html'),
(2, 'Pirotecnia', 2, '2Lvl', 'Transmutación', '1 Acción', '60 pies', 'Instantáneo', 'V, S', 'hechizo_pirotecnia.html'),
(2, 'Ver lo invisible', 2, '2Lvl', 'Adivinación', '1 Acción', 'Personal', '1 hora', 'V, S, M', 'hechizo_ver_invisible.html'),
(2, 'Estallido', 2, '2Lvl', 'Evocación', '1 Acción', '60 pies', 'Instantáneo', 'V, S, M', 'hechizo_estallido.html'),
(2, 'Silencio', 2, '2Lvl', 'Ilusión', '1 Acción R', '120 pies', 'Concentración, hasta 10 minutos', 'V, S', 'hechizo_silencio.html'),
(2, 'Escribir en el cielo', 2, '2Lvl', 'Transmutación', '1 Acción R', 'Visión', 'Concentración, hasta 1 día', 'V, S', 'hechizo_escribir_cielo.html'),
(2, 'Rociada de cartas', 2, '2Lvl', 'Conjuro', '1 Acción', 'Personal (cono de 15 pies)', 'Instantáneo', 'V, S, M', 'hechizo_rociada_cartas.html'),
(2, 'Sugestión', 2, '2Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 8 horas', 'V, M', 'hechizo_sugestion.html'),
(2, 'Viento de protección', 2, '2Lvl', 'Evocación', '1 Acción', 'Personal', 'Concentración, hasta 10 minutos', 'V', 'hechizo_viento_proteccion.html'),
(2, 'Zona de verdad', 2, '2Lvl', 'Encantamiento', '1 Acción', '60 pies', '10 minutos', 'V, S', 'hechizo_zona_verdad.html'),
(2, 'Antagonizar', 3, '3Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Instantáneo', 'V, S, M', 'hechizo_antagonizar.html'),
(2, 'Imponer maldición', 3, '3Lvl', 'Necromancia', '1 Acción', 'Toque', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_imponer_maldicion.html'),
(2, 'Siesta felina', 3, '3Lvl', 'Encantamiento', '1 Acción', '30 pies', '10 minutos', 'S, M', 'hechizo_siesta_felina.html'),
(2, 'Clarividencia', 3, '3Lvl', 'Adivinación', '10 Minutos', '1 milla', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_clarividencia.html'),
(2, 'Disipar magia', 3, '3Lvl', 'Abjuración', '1 Acción', '120 pies', 'Instantáneo', 'V, S', 'hechizo_disipar_magia.html'),
(2, 'Enemigos por doquier', 3, '3Lvl', 'Encantamiento', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_enemigos_doquier.html'),
(2, 'Amigos rápidos', 3, '3Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 hora', 'V', 'hechizo_amigos_rapidos.html'),
(2, 'Miedo', 3, '3Lvl', 'Ilusión', '1 Acción', 'Personal (cono de 30 pies)', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_miedo.html'),
(2, 'Fingir muerte', 3, '3Lvl', 'Necromancia', '1 Acción R', 'Toque', '1 hora', 'V, S, M', 'hechizo_fingir_muerte.html'),
(2, 'Runa guardiana', 3, '3Lvl', 'Abjuración', '1 Hora', 'Toque', 'Hasta ser disipada o activada', 'V, S, M', 'hechizo_runa_guardiana.html'),
(2, 'Casa de cartas (UA)', 3, '3Lvl', 'Conjuro', '1 Minuto', 'Toque', '24 horas', 'V, S, M', 'hechizo_casa_cartas.html'),
(2, 'Patrón hipnótico', 3, '3Lvl', 'Ilusión', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'S, M', 'hechizo_patron_hipnotico.html'),
(2, 'Fortaleza intelectual', 3, '3Lvl', 'Abjuración', '1 Acción', '30 pies', 'Concentración, hasta 1 hora', 'V', 'hechizo_fortaleza_intelectual.html'),
(2, 'Choza diminuta de Leomund', 3, '3Lvl', 'Evocación', '1 Minuto R', 'Personal (hemisferio de 10 pies de radio)', '8 horas', 'V, S, M', 'hechizo_choza_leomund.html'),
(2, 'Imagen mayor', 3, '3Lvl', 'Ilusión', '1 Acción', '120 pies', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_imagen_mayor.html'),
(2, 'Palabra de curación en masa', 3, '3Lvl', 'Evocación', '1 Acción bonus', '60 pies', 'Instantáneo', 'V', 'hechizo_palabra_curacion_masa.html'),
(2, 'Discurso motivacional', 3, '3Lvl', 'Encantamiento', '1 Minuto', '60 pies', '1 hora', 'V', 'hechizo_discurso_motivacional.html'),
(2, 'No detección', 3, '3Lvl', 'Abjuración', '1 Acción', 'Toque', '8 horas', 'V, S, M', 'hechizo_no_deteccion.html'),
(2, 'Crecimiento vegetal', 3, '3Lvl', 'Transmutación', '1 Acción u 8 Horas', '150 pies', 'Instantáneo', 'V, S', 'hechizo_crecimiento_vegetal.html'),
(2, 'Envío', 3, '3Lvl', 'Evocación', '1 Acción', 'Ilimitado', '1 ronda', 'V, S, M', 'hechizo_envio.html'),
(2, 'Lentitud', 3, '3Lvl', 'Transmutación', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_lentitud.html'),
(2, 'Hablar con los muertos', 3, '3Lvl', 'Necromancia', '1 Acción', '10 pies', '10 minutos', 'V, S, M', 'hechizo_hablar_muertos.html'),
(2, 'Hablar con las plantas', 3, '3Lvl', 'Transmutación', '1 Acción', 'Personal (radio de 30 pies)', '10 minutos', 'V, S', 'hechizo_hablar_plantas.html'),
(2, 'Nube apestosa', 3, '3Lvl', 'Conjuro', '1 Acción', '90 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_nube_apestosa.html'),
(2, 'Lenguas', 3, '3Lvl', 'Adivinación', '1 Acción', 'Toque', '1 hora', 'V, M', 'hechizo_lenguas.html'),
(2, 'Hechizar monstruo', 4, '4Lvl', 'Encantamiento', '1 Acción', '30 pies', '1 hora', 'V, S', 'hechizo_hechizar_monstruo.html'),
(2, 'Compulsión', 4, '4Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_compulsion.html'),
(2, 'Confusión', 4, '4Lvl', 'Encantamiento', '1 Acción', '90 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_confusion.html'),
(2, 'Puerta dimensional', 4, '4Lvl', 'Conjuro', '1 Acción', '500 pies', 'Instantáneo', 'V', 'hechizo_puerta_dimensional.html'),
(2, 'Látigo de ego (UA)', 4, '4Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V', 'hechizo_latigo_ego.html'),
(2, 'Libertad de movimiento', 4, '4Lvl', 'Abjuración', '1 Acción', 'Toque', '1 hora', 'V, S, M', 'hechizo_libertad_movimiento.html'),
(2, 'Invisibilidad mayor', 4, '4Lvl', 'Ilusión', '1 Acción', 'Toque', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_invisibilidad_mayor.html'),
(2, 'Terreno alucinatorio', 4, '4Lvl', 'Ilusión', '10 Minutos', '300 pies', '24 horas', 'V, S, M', 'hechizo_terreno_alucinatorio.html'),
(2, 'Localizar criatura', 4, '4Lvl', 'Adivinación', '1 Acción', 'Personal', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_localizar_criatura.html'),
(2, 'Asesino fantasmal', 4, '4Lvl', 'Ilusión', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_asesino_fantasmal.html'),
(2, 'Polimorfar', 4, '4Lvl', 'Transmutación', '1 Acción', '60 pies', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_polimorfar.html'),
(2, 'Lanza psíquica de Raulothim', 4, '4Lvl', 'Encantamiento', '1 Acción', '120 pies', 'Instantáneo', 'V', 'hechizo_lanza_psiquica_raulothim.html'),
(2, 'Objetos animados', 5, '5Lvl', 'Transmutación', '1 Acción', '120 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_objetos_animados.html'),
(2, 'Despertar', 5, '5Lvl', 'Transmutación', '8 Horas', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_despertar.html'),
(2, 'Dominar persona', 5, '5Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_dominar_persona.html'),
(2, 'Sueño', 5, '5Lvl', 'Ilusión', '1 Minuto', 'Especial', '8 horas', 'V, S, M', 'hechizo_sueño.html'),
(2, 'Geas', 5, '5Lvl', 'Encantamiento', '1 Minuto', '60 pies', '30 días', 'V', 'hechizo_geas.html'),
(2, 'Restauración mayor', 5, '5Lvl', 'Abjuración', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_restauracion_mayor.html'),
(2, 'Inmovilizar monstruo', 5, '5Lvl', 'Encantamiento', '1 Acción', '90 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_inmovilizar_monstruo.html'),
(2, 'Leyenda', 5, '5Lvl', 'Adivinación', '10 Minutos', 'Personal', 'Instantáneo', 'V, S, M', 'hechizo_leyenda.html'),
(2, 'Curar heridas en masa', 5, '5Lvl', 'Evocación', '1 Acción', '60 pies', 'Instantáneo', 'V, S', 'hechizo_curar_heridas_masa.html'),
(2, 'Despistar', 5, '5Lvl', 'Ilusión', '1 Acción', 'Personal', 'Concentración, hasta 1 hora', 'S', 'hechizo_despistar.html'),
(2, 'Modificar memoria', 5, '5Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_modificar_memoria.html'),
(2, 'Vinculo planar', 5, '5Lvl', 'Abjuración', '1 Hora', '60 pies', '24 horas', 'V, S, M', 'hechizo_vinculo_planar.html'),
(2, 'Resucitar', 5, '5Lvl', 'Necromancia', '1 Acción', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_resucitar.html'),
(2, 'Vínculo telepático de Rary', 5, '5Lvl', 'Adivinación', '1 Acción R', '30 pies', '1 hora', 'V, S, M', 'hechizo_vinculo_telepatico_rary.html'),
(2, 'Escrutar', 5, '5Lvl', 'Adivinación', '10 Minutos', 'Personal', 'Concentración, hasta 10 minutos', 'V, S, M', 'hechizo_escrutar.html'),
(2, 'Apariencia', 5, '5Lvl', 'Ilusión', '1 Acción', '30 pies', '8 horas', 'V, S', 'hechizo_apariencia.html'),
(2, 'Empoderamiento de habilidades', 5, '5Lvl', 'Transmutación', '1 Acción', 'Toque', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_empoderamiento_habilidades.html'),
(2, 'Estática sináptica', 5, '5Lvl', 'Encantamiento', '1 Acción', '120 pies', 'Instantáneo', 'V, S', 'hechizo_estatica_sinaptica.html'),
(2, 'Círculo de teletransportación', 5, '5Lvl', 'Conjuro', '1 Minuto', '10 pies', '1 ronda', 'V, M', 'hechizo_circulo_teletransportacion.html'),
(2, 'Mirada penetrante', 6, '6Lvl', 'Necromancia', '1 Acción', 'Personal', 'Concentración, hasta 1 minuto', 'V, S', 'hechizo_mirada_penetrante.html'),
(2, 'Encontrar el camino', 6, '6Lvl', 'Adivinación', '1 Minuto', 'Personal', 'Concentración, hasta 1 día', 'V, S, M', 'hechizo_encontrar_camino.html'),
(2, 'Guardianes y custodias', 6, '6Lvl', 'Abjuración', '10 Minutos', 'Toque', '24 horas', 'V, S, M', 'hechizo_guardianes_custodias.html'),
(2, 'Festín de héroes', 6, '6Lvl', 'Conjuro', '10 Minutos', '30 pies', 'Instantáneo', 'V, S, M', 'hechizo_festin_heroes.html'),
(2, 'Sugestión en masa', 6, '6Lvl', 'Encantamiento', '1 Acción', '60 pies', '24 horas', 'V, M', 'hechizo_sugestion_masa.html'),
(2, 'Danza irresistible de Otto', 6, '6Lvl', 'Encantamiento', '1 Acción', '30 pies', 'Concentración, hasta 1 minuto', 'V', 'hechizo_danza_otto.html'),
(2, 'Ilusión programada', 6, '6Lvl', 'Ilusión', '1 Acción', '120 pies', 'Hasta ser disipada', 'V, S, M', 'hechizo_ilusion_programada.html'),
(2, 'Visión verdadera', 6, '6Lvl', 'Adivinación', '1 Acción', 'Toque', '1 hora', 'V, S, M', 'hechizo_vision_verdadera.html'),
(2, 'Sueño del velo azul', 7, '7Lvl', 'Conjuro', '10 minutos', '20 pies', '6 horas', 'V, S, M', 'hechizo_sueño_velo_azul.html'),
(2, 'Etéreo', 7, '7Lvl', 'Transmutación', '1 Acción', 'Personal', 'Hasta 8 horas', 'V, S', 'hechizo_etereo.html'),
(2, 'Jaula de fuerza', 7, '7Lvl', 'Evocación', '1 Acción', '100 pies', '1 hora', 'V, S, M', 'hechizo_jaula_fuerza.html'),
(2, 'Arcano milagroso', 7, '7Lvl', 'Ilusión', '10 Minutos', 'Visión', '10 días', 'V, S', 'hechizo_arcano_milagroso.html'),
(2, 'Magnífica mansión de Mordenkainen', 7, '7Lvl', 'Conjuro', '1 Minuto', '300 pies', '24 horas', 'V, S, M', 'hechizo_mansion_mordenkainen.html'),
(2, 'Espada de Mordenkainen', 7, '7Lvl', 'Evocación', '1 Acción', '60 pies', 'Concentración, hasta 1 minuto', 'V, S, M', 'hechizo_espada_mordenkainen.html'),
(2, 'Rociada prismática', 7, '7Lvl', 'Evocación', '1 Acción', 'Personal (cono de 60 pies)', 'Instantáneo', 'V, S', 'hechizo_rociada_prismatica.html'),
(2, 'Proyectar imagen', 7, '7Lvl', 'Ilusión', '1 Acción', '500 millas', 'Concentración, hasta 1 día', 'V, S, M', 'hechizo_proyectar_imagen.html'),
(2, 'Regenerar', 7, '7Lvl', 'Transmutación', '1 Minuto', 'Toque', '1 hora', 'V, S, M', 'hechizo_regenerar.html'),
(2, 'Resurrección', 7, '7Lvl', 'Necromancia', '1 Hora', 'Toque', 'Instantáneo', 'V, S, M', 'hechizo_resurreccion.html'),
(2, 'Símbolo', 7, '7Lvl', 'Abjuración', '1 Minuto', 'Toque', 'Hasta ser disipado o activado', 'V, S, M', 'hechizo_simbolo.html'),
(2, 'Teletransportar', 7, '7Lvl', 'Conjuro', '1 Acción', '10 pies', 'Instantáneo', 'V', 'hechizo_teletransportar.html'),
(2, 'Antipatía/Simpatía', 8, '8Lvl', 'Encantamiento', '1 Hora', '60 pies', '10 días', 'V, S, M', 'hechizo_antipatia_simpatia.html'),
(2, 'Dominar monstruo', 8, '8Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Concentración, hasta 1 hora', 'V, S', 'hechizo_dominar_monstruo.html'),
(2, 'Mente en blanco', 8, '8Lvl', 'Encantamiento', '1 Acción', '150 pies', 'Instantáneo', 'V, S, M', 'hechizo_mente_blanco.html'),
(2, 'Elocuencia', 8, '8Lvl', 'Transmutación', '1 Acción', 'Personal', '1 hora', 'V', 'hechizo_elocuencia.html'),
(2, 'Mente en blanco', 8, '8Lvl', 'Abjuración', '1 Acción', 'Toque', '24 horas', 'V, S', 'hechizo_mente_blanco.html'),
(2, 'Palabra de poder: Aturdir', 8, '8Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Instantáneo', 'V, S', 'hechizo_palabra_poder_aturdir.html'),
(2, 'Presagio', 9, '9Lvl', 'Adivinación', '1 Minuto', 'Toque', '8 horas', 'V, S, M', 'hechizo_presagio.html'),
(2, 'Polimorfar en masa', 9, '9Lvl', 'Transmutación', '1 Acción', '120 pies', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_polimorfar_masa.html'),
(2, 'Palabra de poder: Sanar', 9, '9Lvl', 'Evocación', '1 Acción', 'Toque', 'Instantáneo', 'V, S', 'hechizo_palabra_poder_sanar.html'),
(2, 'Palabra de poder: Matar', 9, '9Lvl', 'Encantamiento', '1 Acción', '60 pies', 'Instantáneo', 'V', 'hechizo_palabra_poder_matar.html'),
(2, 'Muro prismático', 9, '9Lvl', 'Abjuración', '1 Acción', '60 pies', '10 minutos', 'V, S', 'hechizo_muro_prismatico.html'),
(2, 'Grito psíquico', 9, '9Lvl', 'Encantamiento', '1 Acción', '90 pies', 'Instantáneo', 'S', 'hechizo_grito_psiquico.html'),
(2, 'Polimorfar verdadero', 9, '9Lvl', 'Transmutación', '1 Acción', '30 pies', 'Concentración, hasta 1 hora', 'V, S, M', 'hechizo_polimorfar_verdadero.html');

---->Clerigo
INSERT INTO hechizos (clase_id, nombre, nivel, tipo, enlace) VALUES
(3, 'Descomponer', 0, 'Necromancia', 'hechizo_descomponer.html'),
(3, 'Guía', 0, 'Adivinación', 'hechizo_guia.html'),
(3, 'Mano de Resplandor', 0, 'Evocación', 'hechizo_mano_resplandor.html'),
(3, 'Luz', 0, 'Evocación', 'hechizo_luz.html'),
(3, 'Remendar', 0, 'Transmutación', 'hechizo_remendar.html'),
(3, 'Resistencia', 0, 'Abjuración', 'hechizo_resistencia.html'),
(3, 'Llama Sagrada', 0, 'Evocación', 'hechizo_llama_sagrada.html'),
(3, 'Maldición', 1, 'Encantamiento', 'hechizo_maldicion.html'),
(3, 'Bendición', 1, 'Encantamiento', 'hechizo_bendicion.html'),
(3, 'Ceremonia', 1, 'Evocación', 'hechizo_ceremonia.html'),
(3, 'Orden', 1, 'Encantamiento', 'hechizo_orden.html'),
(3, 'Crear o Destruir Agua', 1, 'Transmutación', 'hechizo_crear_destruir_agua.html'),
(3, 'Curar Heridas', 1, 'Evocación', 'hechizo_curar_heridas.html'),
(3, 'Detectar el Bien y el Mal', 1, 'Adivinación', 'hechizo_detectar_bien_mal.html'),
(3, 'Detectar Magia', 1, 'Adivinación', 'hechizo_detectar_magia.html'),
(3, 'Infligir Heridas', 1, 'Necromancia', 'hechizo_infligir_heridas.html'),
(3, 'Protección contra el Bien y el Mal', 1, 'Abjuración', 'hechizo_proteccion_bien_mal.html'),
(3, 'Purificar Comida y Bebida', 1, 'Transmutación', 'hechizo_purificar_comida.html'),
(3, 'Santuario', 1, 'Abjuración', 'hechizo_santuario.html'),
(3, 'Escudo de Fe', 1, 'Abjuración', 'hechizo_escudo_fe.html'),
(3, 'Ayuda', 2, 'Abjuración', 'hechizo_ayuda.html'),
(3, 'Adivinación', 2, 'Adivinación', 'hechizo_adivinacion.html'),
(3, 'Ceguera/Sordera', 2, 'Necromancia', 'hechizo_ceguera_sordera.html'),
(3, 'Conocimiento Prestado', 2, 'Adivinación', 'hechizo_conocimiento_prestado.html'),
(3, 'Calmar Emociones', 2, 'Encantamiento', 'hechizo_calmar_emociones.html'),
(3, 'Llama Continua', 2, 'Evocación', 'hechizo_llama_continua.html'),
(3, 'Mejorar Habilidad', 2, 'Transmutación', 'hechizo_mejorar_habilidad.html'),
(3, 'Encontrar Trampas', 2, 'Adivinación', 'hechizo_encontrar_trampas.html'),
(3, 'Reposo Tranquilo', 2, 'Necromancia', 'hechizo_reposo_tranquilo.html'),
(3, 'Inmovilizar Persona', 2, 'Encantamiento', 'hechizo_inmovilizar_persona.html'),
(3, 'Restauración Menor', 2, 'Abjuración', 'hechizo_restauracion_menor.html'),
(3, 'Localizar Objeto', 2, 'Adivinación', 'hechizo_localizar_objeto.html'),
(3, 'Oración de Curación', 2, 'Evocación', 'hechizo_oracion_curacion.html'),
(3, 'Protección contra Veneno', 2, 'Abjuración', 'hechizo_proteccion_veneno.html'),
(3, 'Silencio', 2, 'Ilusión', 'hechizo_silencio.html'),
(3, 'Arma Espiritual', 2, 'Evocación', 'hechizo_arma_espiritual.html'),
(3, 'Vínculo Protector', 2, 'Abjuración', 'hechizo_vinculo_protector.html'),
(3, 'Zona de Verdad', 2, 'Encantamiento', 'hechizo_zona_verdad.html'),
(3, 'Animación de Muertos', 3, 'Necromancia', 'hechizo_animacion_muertos.html'),
(3, 'Aura de Vitalidad', 3, 'Evocación', 'hechizo_aura_vitalidad.html'),
(3, 'Faro de Esperanza', 3, 'Abjuración', 'hechizo_faro_esperanza.html'),
(3, 'Imponer Maldición', 3, 'Necromancia', 'hechizo_imponer_maldicion.html'),
(3, 'Clarividencia', 3, 'Adivinación', 'hechizo_clarividencia.html'),
(3, 'Crear Comida y Agua', 3, 'Conjuro', 'hechizo_crear_comida_agua.html'),
(3, 'Luz Diurna', 3, 'Evocación', 'hechizo_luz_diurna.html'),
(3, 'Disipar Magia', 3, 'Abjuración', 'hechizo_disipar_magia.html'),
(3, 'Amigos Rápidos', 3, 'Encantamiento', 'hechizo_amigos_rapidos.html'),
(3, 'Fingir Muerte', 3, 'Necromancia', 'hechizo_fingir_muerte.html'),
(3, 'Runa Guardiana', 3, 'Abjuración', 'hechizo_runa_guardiana.html'),
(3, 'Incitar Codicia', 3, 'Encantamiento', 'hechizo_incitar_codicia.html'),
(3, 'Transferencia de Vida', 3, 'Necromancia', 'hechizo_transferencia_vida.html'),
(3, 'Círculo Mágico', 3, 'Abjuración', 'hechizo_circulo_magico.html'),
(3, 'Palabra de Curación en Masa', 3, 'Evocación', 'hechizo_palabra_curacion_masa.html'),
(3, 'Fusionarse con Piedra', 3, 'Transmutación', 'hechizo_fusionarse_piedra.html'),
(3, 'Discurso Motivacional', 3, 'Encantamiento', 'hechizo_discurso_motivacional.html'),
(3, 'Protección contra Energía', 3, 'Abjuración', 'hechizo_proteccion_energia.html'),
(3, 'Quitar Maldición', 3, 'Abjuración', 'hechizo_quitar_maldicion.html'),
(3, 'Revivir', 3, 'Necromancia', 'hechizo_revivir.html'),
(3, 'Envío', 3, 'Evocación', 'hechizo_envio.html'),
(3, 'Hablar con los Muertos', 3, 'Necromancia', 'hechizo_hablar_muertos.html'),
(3, 'Guardianes Espirituales', 3, 'Conjuro', 'hechizo_guardianes_espirituales.html'),
(3, 'Saya Espiritual', 3, 'Necromancia', 'hechizo_saya_espiritual.html'),
(3, 'Lenguas', 3, 'Adivinación', 'hechizo_lenguas.html'),
(3, 'Caminar sobre el Agua', 3, 'Transmutación', 'hechizo_caminar_agua.html'),
(3, 'Aura de Vida', 4, 'Abjuración', 'hechizo_aura_vida.html'),
(3, 'Aura de Pureza', 4, 'Abjuración', 'hechizo_aura_pureza.html'),
(3, 'Desterrar', 4, 'Abjuración', 'hechizo_desterrar.html'),
(3, 'Controlar Agua', 4, 'Transmutación', 'hechizo_controlar_agua.html'),
(3, 'Protección contra la Muerte', 4, 'Abjuración', 'hechizo_proteccion_muerte.html'),
(3, 'Adivinación', 4, 'Adivinación', 'hechizo_adivinacion.html'),
(3, 'Libertad de Movimiento', 4, 'Abjuración', 'hechizo_libertad_movimiento.html'),
(3, 'Guardián de la Fe', 4, 'Conjuro', 'hechizo_guardian_fe.html'),
(3, 'Localizar Criatura', 4, 'Adivinación', 'hechizo_localizar_criatura.html'),
(3, 'Formar Piedra', 4, 'Transmutación', 'hechizo_formar_piedra.html'),
(3, 'Comunión', 5, 'Adivinación', 'hechizo_comunion.html'),
(3, 'Contagio', 5, 'Necromancia', 'hechizo_contagio.html'),
(3, 'Amanecer', 5, 'Evocación', 'hechizo_amanecer.html'),
(3, 'Disipar el Bien y el Mal', 5, 'Abjuración', 'hechizo_disipar_bien_mal.html'),
(3, 'Golpe de Fuego', 5, 'Evocación', 'hechizo_golpe_fuego.html'),
(3, 'Geas', 5, 'Encantamiento', 'hechizo_geas.html'),
(3, 'Restauración Mayor', 5, 'Abjuración', 'hechizo_restauracion_mayor.html'),
(3, 'Consagrar', 5, 'Evocación', 'hechizo_consagrar.html'),
(3, 'Arma Sagrada', 5, 'Evocación', 'hechizo_arma_sagrada.html'),
(3, 'Plaga de Insectos', 5, 'Conjuro', 'hechizo_plaga_insectos.html'),
(3, 'Leyenda', 5, 'Adivinación', 'hechizo_leyenda.html'),
(3, 'Curar Heridas en Masa', 5, 'Evocación', 'hechizo_curar_heridas_masa.html'),
(3, 'Vinculo Planar', 5, 'Abjuración', 'hechizo_vinculo_planar.html'),
(3, 'Resucitar', 5, 'Necromancia', 'hechizo_resucitar.html'),
(3, 'Escrutar', 5, 'Adivinación', 'hechizo_escrutar.html'),
(3, 'Invocar Celestial', 5, 'Conjuro', 'hechizo_invocar_celestial.html'),
(3, 'Puño de hierro', 5, 'Evocación', 'hechizo_puño_iron.html'),
(3, 'Barrera de Espadas', 6, 'Evocación', 'hechizo_barrera_espadas.html'),
(3, 'Crear No Muerto', 6, 'Necromancia', 'hechizo_crear_no_muerto.html'),
(3, 'Encontrar el Camino', 6, 'Adivinación', 'hechizo_encontrar_camino.html'),
(3, 'Prohibición', 6, 'Abjuración', 'hechizo_prohibicion.html'),
(3, 'Dañar', 6, 'Necromancia', 'hechizo_dañar.html'),
(3, 'Sanar', 6, 'Evocación', 'hechizo_sanar.html'),
(3, 'Festín de Héroes', 6, 'Conjuro', 'hechizo_festin_heroes.html'),
(3, 'Forma de Otro Mundo', 6, 'Transmutación', 'hechizo_forma_otro_mundo.html'),
(3, 'Aliado Planar', 6, 'Conjuro', 'hechizo_aliado_planar.html'),
(3, 'Rayo de Sol', 6, 'Evocación', 'hechizo_rayo_sol.html'),
(3, 'Visión Verdadera', 6, 'Adivinación', 'hechizo_vision_verdadera.html'),
(3, 'Palabra de Retorno', 6, 'Conjuro', 'hechizo_palabra_retorno.html'),
(3, 'Conjurar Celestial', 7, 'Conjuro', 'hechizo_conjurar_celestial.html'),
(3, 'Palabra Divina', 7, 'Evocación', 'hechizo_palabra_divina.html'),
(3, 'Etéreo', 7, 'Transmutación', 'hechizo_etereo.html'),
(3, 'Tormenta de Fuego', 7, 'Evocación', 'hechizo_tormenta_fuego.html'),
(3, 'Cambio de Plano', 7, 'Conjuro', 'hechizo_cambio_plano.html'),
(3, 'Regenerar', 7, 'Transmutación', 'hechizo_regenerar.html'),
(3, 'Resurrección', 7, 'Necromancia', 'hechizo_resurreccion.html'),
(3, 'Símbolo', 7, 'Abjuración', 'hechizo_simbolo.html'),
(3, 'Templo de los Dioses', 7, 'Conjuro', 'hechizo_templo_dioses.html'),
(3, 'Campo Antimagia', 8, 'Abjuración', 'hechizo_campo_antimagia.html'),
(3, 'Controlar Clima', 8, 'Transmutación', 'hechizo_controlar_clima.html'),
(3, 'Terremoto', 8, 'Evocación', 'hechizo_terremoto.html'),
(3, 'Aura Sagrada', 8, 'Abjuración', 'hechizo_aura_sagrada.html'),
(3, 'Estallido Solar', 8, 'Evocación', 'hechizo_estallido_solar.html'),
(3, 'Proyección Astral', 9, 'Evocación', 'hechizo_proyeccion_astral.html'),
(3, 'Portal', 9, 'Conjuro', 'hechizo_portal.html'),
(3, 'Sanación en Masa', 9, 'Evocación', 'hechizo_sanacion_masa.html'),
(3, 'Palabra de Poder: Sanar', 9, 'Evocación', 'hechizo_palabra_poder_sanar.html'),
(3, 'Resurrección Verdadera', 9, 'Necromancia', 'hechizo_resurreccion_verdadera.html');

------>Druida
INSERT INTO hechizos (clase_id, nombre, nivel, tipo, enlace)
VALUES
(4, 'Controlar Llamas', 0, 'Transmutación', 'hechizo_controlar_llamas.html'),
(4, 'Crear Fogata', 0, 'Conjuro', 'hechizo_crear_fogata.html'),
(4, 'Truco Druídico', 0, 'Transmutación', 'hechizo_truco_druidico.html'),
(4, 'Mordisco de Escarcha', 0, 'Evocación', 'hechizo_mordisco_escarcha.html'),
(4, 'Guía', 0, 'Adivinación', 'hechizo_guia.html'),
(4, 'Ráfaga', 0, 'Transmutación', 'hechizo_rafaga.html'),
(4, 'Infestación', 0, 'Conjuro', 'hechizo_infestacion.html'),
(4, 'Piedra Mágica', 0, 'Transmutación', 'hechizo_piedra_magica.html'),
(4, 'Remendar', 0, 'Transmutación', 'hechizo_remendar.html'),
(4, 'Moldear Tierra', 0, 'Transmutación', 'hechizo_moldear_tierra.html'),
(4, 'Rociada Venenosa', 0, 'Conjuro', 'hechizo_rociada_venenosa.html'),
(4, 'Ferocidad Primal', 0, 'Transmutación', 'hechizo_ferocidad_primal.html'),
(4, 'Producir Llama', 0, 'Conjuro', 'hechizo_producir_llama.html'),
(4, 'Resistencia', 0, 'Abjuración', 'hechizo_resistencia.html'),
(4, 'Formar Agua', 0, 'Transmutación', 'hechizo_formar_agua.html'),
(4, 'Garrote Mágico', 0, 'Transmutación', 'hechizo_garrote_magico.html'),
(4, 'Látigo de Espinas', 0, 'Transmutación', 'hechizo_latigo_espinas.html'),
(4, 'Estallido de Trueno', 0, 'Evocación', 'hechizo_estallido_trueno.html'),
(4, 'Absorber Elementos', 1, 'Abjuración', 'hechizo_absorber_elementos.html'),
(4, 'Amistad con Animales', 1, 'Encantamiento', 'hechizo_amistad_animales.html'),
(4, 'Vínculo con Bestia', 1, 'Adivinación', 'hechizo_vinculo_bestia.html'),
(4, 'Hechizar Persona', 1, 'Encantamiento', 'hechizo_hechizar_persona.html'),
(4, 'Crear o Destruir Agua', 1, 'Transmutación', 'hechizo_crear_destruir_agua.html'),
(4, 'Curar Heridas', 1, 'Evocación', 'hechizo_curar_heridas.html'),
(4, 'Detectar Magia', 1, 'Adivinación', 'hechizo_detectar_magia.html'),
(4, 'Detectar Veneno y Enfermedad', 1, 'Adivinación', 'hechizo_detectar_veneno_enfermedad.html'),
(4, 'Temblor de Tierra', 1, 'Evocación', 'hechizo_temblor_tierra.html'),
(4, 'Enmarañar', 1, 'Conjuro', 'hechizo_enmarañar.html'),
(4, 'Fuego Feérico', 1, 'Evocación', 'hechizo_fuego_feerico.html'),
(4, 'Nube de Niebla', 1, 'Conjuro', 'hechizo_nube_niebla.html'),
(4, 'Baya Nutritiva', 1, 'Transmutación', 'hechizo_baya_nutritiva.html'),
(4, 'Mano Guía', 1, 'Adivinación', 'hechizo_mano_guia.html'),
(4, 'Palabra Curativa', 1, 'Evocación', 'hechizo_palabra_curativa.html'),
(4, 'Cuchillo de Hielo', 1, 'Conjuro', 'hechizo_cuchillo_hielo.html'),
(4, 'Salto', 1, 'Transmutación', 'hechizo_salto.html'),
(4, 'Zancada Larga', 1, 'Transmutación', 'hechizo_zancada_larga.html'),
(4, 'Protección contra el Bien y el Mal', 1, 'Abjuración', 'hechizo_proteccion_bien_mal.html'),
(4, 'Purificar Comida y Bebida', 1, 'Transmutación', 'hechizo_purificar_comida.html'),
(4, 'Trampa', 1, 'Abjuración', 'hechizo_trampa.html'),
(4, 'Hablar con Animales', 1, 'Adivinación', 'hechizo_hablar_animales.html'),
(4, 'Onda de Trueno', 1, 'Evocación', 'hechizo_onda_trueno.html'),
(4, 'Astucia Salvaje', 1, 'Transmutación', 'hechizo_astucia_salvaje.html'),
(4, 'Burbuja de Aire', 2, 'Conjuro', 'hechizo_burbuja_aire.html'),
(4, 'Mensajero Animal', 2, 'Encantamiento', 'hechizo_mensajero_animal.html'),
(4, 'Adivinación', 2, 'Adivinación', 'hechizo_adivinacion.html'),
(4, 'Piel de Corteza', 2, 'Transmutación', 'hechizo_piel_corteza.html'),
(4, 'Sentido Bestial', 2, 'Adivinación', 'hechizo_sentido_bestial.html'),
(4, 'Llama Continua', 2, 'Evocación', 'hechizo_llama_continua.html'),
(4, 'Visión en la Oscuridad', 2, 'Transmutación', 'hechizo_vision_oscuridad.html'),
(4, 'Demonio de Polvo', 2, 'Conjuro', 'hechizo_demonio_polvo.html'),
(4, 'Atadura Terrenal', 2, 'Transmutación', 'hechizo_atadura_terrenal.html'),
(4, 'Mejorar Habilidad', 2, 'Transmutación', 'hechizo_mejorar_habilidad.html'),
(4, 'Agrandar/Reducir', 2, 'Transmutación', 'hechizo_agrandar_reducir.html'),
(4, 'Encontrar Trampas', 2, 'Adivinación', 'hechizo_encontrar_trampas.html'),
(4, 'Espada Llameante', 2, 'Evocación', 'hechizo_espada_llameante.html'),
(4, 'Esfera Flameante', 2, 'Conjuro', 'hechizo_esfera_flameante.html'),
(4, 'Ráfaga de Viento', 2, 'Evocación', 'hechizo_rafaga_viento.html'),
(4, 'Espíritu Curativo', 2, 'Conjuro', 'hechizo_espiritu_curativo.html'),
(4, 'Calentar Metal', 2, 'Transmutación', 'hechizo_calentar_metal.html'),
(4, 'Inmovilizar Persona', 2, 'Encantamiento', 'hechizo_inmovilizar_persona.html'),
(4, 'Restauración Menor', 2, 'Abjuración', 'hechizo_restauracion_menor.html'),
(4, 'Localizar Animales o Plantas', 2, 'Adivinación', 'hechizo_localizar_animales_plantas.html'),
(4, 'Localizar Objeto', 2, 'Adivinación', 'hechizo_localizar_objeto.html'),
(4, 'Rayo Lunar', 2, 'Evocación', 'hechizo_rayo_lunar.html'),
(4, 'Pasar sin Rastro', 2, 'Abjuración', 'hechizo_pasar_sin_rastro.html'),
(4, 'Protección contra Veneno', 2, 'Abjuración', 'hechizo_proteccion_veneno.html'),
(4, 'Escribir en el Cielo', 2, 'Transmutación', 'hechizo_escribir_cielo.html'),
(4, 'Crecimiento de Espinas', 2, 'Transmutación', 'hechizo_crecimiento_espinas.html'),
(4, 'Invocar Bestia', 2, 'Conjuro', 'hechizo_invocar_bestia.html'),
(4, 'Viento de Protección', 2, 'Evocación', 'hechizo_viento_proteccion.html'),
(4, 'Marchitar y Florecer', 2, 'Necromancia', 'hechizo_marchitar_florecer.html'),
(4, 'Aura de Vitalidad', 3, 'Evocación', 'hechizo_aura_vitalidad.html'),
(4, 'Invocar Relámpago', 3, 'Conjuro', 'hechizo_invocar_relampago.html'),
(4, 'Conjurar Animales', 3, 'Conjuro', 'hechizo_conjurar_animales.html'),
(4, 'Luz Diurna', 3, 'Evocación', 'hechizo_luz_diurna.html'),
(4, 'Disipar Magia', 3, 'Abjuración', 'hechizo_disipar_magia.html'),
(4, 'Arma Elemental', 3, 'Transmutación', 'hechizo_arma_elemental.html'),
(4, 'Tierra en Erupción', 3, 'Transmutación', 'hechizo_tierra_erupcion.html'),
(4, 'Fingir Muerte', 3, 'Necromancia', 'hechizo_fingir_muerte.html'),
(4, 'Flechas Llameantes', 3, 'Transmutación', 'hechizo_flechas_llameantes.html'),
(4, 'Libertad de las Olas', 3, 'Conjuro HB', 'hechizo_libertad_olas.html'),
(4, 'Fusionarse con Piedra', 3, 'Transmutación', 'hechizo_fusionarse_piedra.html'),
(4, 'Crecimiento Vegetal', 3, 'Transmutación', 'hechizo_crecimiento_vegetal.html'),
(4, 'Protección contra Energía', 3, 'Abjuración', 'hechizo_proteccion_energia.html'),
(4, 'Revivir', 3, 'Necromancia', 'hechizo_revivir.html'),
(4, 'Tormenta de Aguanieve', 3, 'Conjuro', 'hechizo_tormenta_aguanieve.html'),
(4, 'Hablar con Plantas', 3, 'Transmutación', 'hechizo_hablar_plantas.html'),
(4, 'Invocar Fey', 3, 'Conjuro', 'hechizo_invocar_fey.html'),
(4, 'Ola de Marea', 3, 'Conjuro', 'hechizo_ola_marea.html'),
(4, 'Muro de Agua', 3, 'Evocación', 'hechizo_muro_agua.html'),
(4, 'Respiración Acuática', 3, 'Transmutación', 'hechizo_respiracion_acuatica.html'),
(4, 'Caminar sobre el Agua', 3, 'Transmutación', 'hechizo_caminar_agua.html'),
(4, 'Muro de Viento', 3, 'Evocación', 'hechizo_muro_viento.html'),
(4, 'Marchitar', 4, 'Necromancia', 'hechizo_marchitar.html'),
(4, 'Hechizar Monstruo', 4, 'Encantamiento', 'hechizo_hechizar_monstruo.html'),
(4, 'Confusión', 4, 'Encantamiento', 'hechizo_confusion.html'),
(4, 'Conjurar Elementales Menores', 4, 'Conjuro', 'hechizo_conjurar_elementales_menores.html'),
(4, 'Conjurar Seres del Bosque', 4, 'Conjuro', 'hechizo_conjurar_seres_bosque.html'),
(4, 'Controlar Agua', 4, 'Transmutación', 'hechizo_controlar_agua.html'),
(4, 'Adivinación', 4, 'Adivinación', 'hechizo_adivinacion.html'),
(4, 'Dominar Bestia', 4, 'Encantamiento', 'hechizo_dominar_bestia.html'),
(4, 'Maldición Elemental', 4, 'Transmutación', 'hechizo_maldicion_elemental.html'),
(4, 'Escudo de Fuego', 4, 'Evocación', 'hechizo_escudo_fuego.html'),
(4, 'Libertad de Movimiento', 4, 'Abjuración', 'hechizo_libertad_movimiento.html'),
(4, 'Insecto Gigante', 4, 'Transmutación', 'hechizo_insecto_gigante.html'),
(4, 'Enredadera Aferrante', 4, 'Conjuro', 'hechizo_enredadera_aferrante.html'),
(4, 'Guardián de la Naturaleza', 4, 'Transmutación', 'hechizo_guardian_naturaleza.html'),
(4, 'Terreno Alucinatorio', 4, 'Ilusión', 'hechizo_terreno_alucinatorio.html'),
(4, 'Tormenta de Hielo', 4, 'Evocación', 'hechizo_tormenta_hielo.html'),
(4, 'Localizar Criatura', 4, 'Adivinación', 'hechizo_localizar_criatura.html'),
(4, 'Polimorfar', 4, 'Transmutación', 'hechizo_polimorfar.html'),
(4, 'Formar Piedra', 4, 'Transmutación', 'hechizo_formar_piedra.html'),
(4, 'Piel de Piedra', 4, 'Abjuración', 'hechizo_piel_piedra.html'),
(4, 'Invocar Elemental', 4, 'Conjuro', 'hechizo_invocar_elemental.html'),
(4, 'Muro de Fuego', 4, 'Evocación', 'hechizo_muro_fuego.html'),
(4, 'Esfera Acuática', 4, 'Conjuro', 'hechizo_esfera_acuatica.html'),
(4, 'Coraza Antivida', 5, 'Abjuración', 'hechizo_coraza_antivida.html'),
(4, 'Despertar', 5, 'Transmutación', 'hechizo_despertar.html'),
(4, 'Comulgar con la Naturaleza', 5, 'Adivinación', 'hechizo_comulgar_naturaleza.html'),
(4, 'Cono de Frío', 5, 'Evocación', 'hechizo_cono_frio.html'),
(4, 'Conjurar Elemental', 5, 'Conjuro', 'hechizo_conjurar_elemental.html'),
(4, 'Contagio', 5, 'Necromancia', 'hechizo_contagio.html'),
(4, 'Controlar Vientos', 5, 'Transmutación', 'hechizo_controlar_vientos.html'),
(4, 'Libertad de los Vientos', 5, 'Abjuración HB', 'hechizo_libertad_vientos.html'),
(4, 'Geas', 5, 'Encantamiento', 'hechizo_geas.html'),
(4, 'Restauración Mayor', 5, 'Abjuración', 'hechizo_restauracion_mayor.html'),
(4, 'Plaga de Insectos', 5, 'Conjuro', 'hechizo_plaga_insectos.html'),
(4, 'Torbellino', 5, 'Evocación', 'hechizo_torbellino.html'),
(4, 'Curar Heridas en Masa', 5, 'Evocación', 'hechizo_curar_heridas_masa.html'),
(4, 'Vinculo Planar', 5, 'Abjuración', 'hechizo_vinculo_planar.html'),
(4, 'Reencarnar', 5, 'Transmutación', 'hechizo_reencarnar.html'),
(4, 'Escrutar', 5, 'Adivinación', 'hechizo_escrutar.html'),
(4, 'Invocar Espíritu Dracónico', 5, 'Conjuro', 'hechizo_invocar_espiritu_draconico.html'),
(4, 'Transmutar Roca', 5, 'Transmutación', 'hechizo_transmutar_roca.html'),
(4, 'Paso entre Árboles', 5, 'Conjuro', 'hechizo_paso_entre_arboles.html'),
(4, 'Muro de Piedra', 5, 'Evocación', 'hechizo_muro_piedra.html'),
(4, 'Cólera de la Naturaleza', 5, 'Evocación', 'hechizo_colera_naturaleza.html'),
(4, 'Huesos de la Tierra', 6, 'Transmutación', 'hechizo_huesos_tierra.html'),
(4, 'Conjurar Fey', 6, 'Conjuro', 'hechizo_conjurar_fey.html'),
(4, 'Arboleda Druídica', 6, 'Abjuración', 'hechizo_arboleda_druidica.html'),
(4, 'Encontrar el Camino', 6, 'Adivinación', 'hechizo_encontrar_camino.html'),
(4, 'Carne a Piedra', 6, 'Transmutación', 'hechizo_carne_piedra.html'),
(4, 'Sanar', 6, 'Evocación', 'hechizo_sanar.html'),
(4, 'Festín de Héroes', 6, 'Conjuro', 'hechizo_festin_heroes.html'),
(4, 'Investidura de Fuego', 6, 'Transmutación', 'hechizo_investidura_fuego.html'),
(4, 'Investidura de Hielo', 6, 'Transmutación', 'hechizo_investidura_hielo.html'),
(4, 'Investidura de Piedra', 6, 'Transmutación', 'hechizo_investidura_piedra.html'),
(4, 'Investidura de Viento', 6, 'Transmutación', 'hechizo_investidura_viento.html'),
(4, 'Mover Tierra', 6, 'Transmutación', 'hechizo_mover_tierra.html'),
(4, 'Protección Primordial', 6, 'Abjuración', 'hechizo_proteccion_primordial.html'),
(4, 'Rayo de Sol', 6, 'Evocación', 'hechizo_rayo_sol.html'),
(4, 'Transporte Vegetal', 6, 'Conjuro', 'hechizo_transporte_vegetal.html'),
(4, 'Muro de Espinas', 6, 'Conjuro', 'hechizo_muro_espinas.html'),
(4, 'Caminar con el Viento', 6, 'Transmutación', 'hechizo_caminar_viento.html'),
(4, 'Transformación Dracónica', 7, 'Transmutación', 'hechizo_transformacion_draconica.html'),
(4, 'Tormenta de Fuego', 7, 'Evocación', 'hechizo_tormenta_fuego.html'),
(4, 'Arcano Milagroso', 7, 'Ilusión', 'hechizo_arcano_milagroso.html'),
(4, 'Cambio de Plano', 7, 'Conjuro', 'hechizo_cambio_plano.html'),
(4, 'Regenerar', 7, 'Transmutación', 'hechizo_regenerar.html'),
(4, 'Gravedad Inversa', 7, 'Transmutación', 'hechizo_gravedad_inversa.html'),
(4, 'Símbolo', 7, 'Abjuración', 'hechizo_simbolo.html'),
(4, 'Torbellino', 7, 'Evocación', 'hechizo_torbellino.html'),
(4, 'Formas Animales', 8, 'Transmutación', 'hechizo_formas_animales.html'),
(4, 'Antipatía/Simpatía', 8, 'Encantamiento', 'hechizo_antipatia_simpatia.html'),
(4, 'Controlar Clima', 8, 'Transmutación', 'hechizo_controlar_clima.html'),
(4, 'Terremoto', 8, 'Evocación', 'hechizo_terremoto.html'),
(4, 'Mente en Blanco', 8, 'Encantamiento', 'hechizo_mente_blanco.html'),
(4, 'Nube Incendiaria', 8, 'Conjuro', 'hechizo_nube_incendiaria.html'),
(4, 'Estallido Solar', 8, 'Evocación', 'hechizo_estallido_solar.html'),
(4, 'Tsunami', 8, 'Conjuro', 'hechizo_tsunami.html'),
(4, 'Presagio', 9, 'Adivinación', 'hechizo_presagio.html'),
(4, 'Cambio de Forma', 9, 'Transmutación', 'hechizo_cambio_forma.html'),
(4, 'Tormenta de Venganza', 9, 'Conjuro', 'hechizo_tormenta_venganza.html'),
(4, 'Resurrección Verdadera', 9, 'Necromancia', 'hechizo_resurreccion_verdadera.html');

----->Guardabosque
INSERT INTO hechizos (clase_id, nombre, nivel, tipo, enlace) VALUES
(5, 'Bless', 1, 'Enchantment', 'hechizo_bless.html'),
(5, 'Ceremony', 1, 'Evocation', 'hechizo_ceremony.html'),
(5, 'Command', 1, 'Enchantment', 'hechizo_command.html'),
(5, 'Compelled Duel', 1, 'Enchantment', 'hechizo_compelled_duel.html'),
(5, 'Cure Wounds', 1, 'Evocation', 'hechizo_cure_wounds.html'),
(5, 'Detect Evil and Good', 1, 'Divination', 'hechizo_detect_evil_and_good.html'),
(5, 'Detect Magic', 1, 'Divination', 'hechizo_detect_magic.html'),
(5, 'Detect Poison and Disease', 1, 'Divination', 'hechizo_detect_poison_and_disease.html'),
(5, 'Divine Favor', 1, 'Evocation', 'hechizo_divine_favor.html'),
(5, 'Heroism', 1, 'Enchantment', 'hechizo_heroism.html'),
(5, 'Protection from Evil and Good', 1, 'Abjuration', 'hechizo_protection_from_evil_and_good.html'),
(5, 'Purify Food and Drink', 1, 'Transmutation', 'hechizo_purify_food_and_drink.html'),
(5, 'Searing Smite', 1, 'Evocation', 'hechizo_searing_smite.html'),
(5, 'Shield of Faith', 1, 'Abjuration', 'hechizo_shield_of_faith.html'),
(5, 'Thunderous Smite', 1, 'Evocation', 'hechizo_thunderous_smite.html'),
(5, 'Wrathful Smite', 1, 'Evocation', 'hechizo_wrathful_smite.html'),
(5, 'Aid', 2, 'Abjuration', 'hechizo_aid.html'),
(5, 'Branding Smite', 2, 'Evocation', 'hechizo_branding_smite.html'),
(5, 'Find Steed', 2, 'Conjuration', 'hechizo_find_steed.html'),
(5, 'Find Vehicle (UA)', 2, 'Conjuration T', 'hechizo_find_vehicle.html'),
(5, 'Gentle Repose', 2, 'Necromancy', 'hechizo_gentle_repose.html'),
(5, 'Lesser Restoration', 2, 'Abjuration', 'hechizo_lesser_restoration.html'),
(5, 'Locate Object', 2, 'Divination', 'hechizo_locate_object.html'),
(5, 'Magic Weapon', 2, 'Transmutation', 'hechizo_magic_weapon.html'),
(5, 'Prayer of Healing', 2, 'Evocation', 'hechizo_prayer_of_healing.html'),
(5, 'Protection from Poison', 2, 'Abjuration', 'hechizo_protection_from_poison.html'),
(5, 'Warding Bond', 2, 'Abjuration', 'hechizo_warding_bond.html'),
(5, 'Zone of Truth', 2, 'Enchantment', 'hechizo_zone_of_truth.html'),
(5, 'Aura of Vitality', 3, 'Evocation', 'hechizo_aura_of_vitality.html'),
(5, 'Blinding Smite', 3, 'Evocation', 'hechizo_blinding_smite.html'),
(5, 'Create Food and Water', 3, 'Conjuration', 'hechizo_create_food_and_water.html'),
(5, 'Crusaders Mantle', 3, 'Evocation', 'hechizo_crusaders_mantle.html'),
(5, 'Daylight', 3, 'Evocation', 'hechizo_daylight.html'),
(5, 'Dispel Magic', 3, 'Abjuration', 'hechizo_dispel_magic.html'),
(5, 'Elemental Weapon', 3, 'Transmutation', 'hechizo_elemental_weapon.html'),
(5, 'Magic Circle', 3, 'Abjuration', 'hechizo_magic_circle.html'),
(5, 'Remove Curse', 3, 'Abjuration', 'hechizo_remove_curse.html'),
(5, 'Revivify', 3, 'Necromancy', 'hechizo_revivify.html'),
(5, 'Spirit Shroud', 3, 'Necromancy', 'hechizo_spirit_shroud.html'),
(5, 'Aura of Life', 4, 'Abjuration', 'hechizo_aura_of_life.html'),
(5, 'Aura of Purity', 4, 'Abjuration', 'hechizo_aura_of_purity.html'),
(5, 'Banishment', 4, 'Abjuration', 'hechizo_banishment.html'),
(5, 'Death Ward', 4, 'Abjuration', 'hechizo_death_ward.html'),
(5, 'Find Greater Steed', 4, 'Conjuration', 'hechizo_find_greater_steed.html'),
(5, 'Locate Creature', 4, 'Divination', 'hechizo_locate_creature.html'),
(5, 'Staggering Smite', 4, 'Evocation', 'hechizo_staggering_smite.html'),
(5, 'Banishing Smite', 5, 'Abjuration', 'hechizo_banishing_smite.html'),
(5, 'Circle of Power', 5, 'Abjuration', 'hechizo_circle_of_power.html'),
(5, 'Destructive Wave', 5, 'Evocation', 'hechizo_destructive_wave.html'),
(5, 'Dispel Evil and Good', 5, 'Abjuration', 'hechizo_dispel_evil_and_good.html'),
(5, 'Geas', 5, 'Enchantment', 'hechizo_geas.html'),
(5, 'Holy Weapon', 5, 'Evocation', 'hechizo_holy_weapon.html'),
(5, 'Raise Dead', 5, 'Necromancy', 'hechizo_raise_dead.html'),
(5, 'Summon Celestial', 5, 'Conjuration', 'hechizo_summon_celestial.html');

---->Paladin
INSERT INTO hechizos (clase_id, nombre, nivel, tipo, enlace) VALUES
(5, 'Bless', 1, 'Enchantment', 'hechizo_bless.html'),
(5, 'Ceremony', 1, 'Evocation', 'hechizo_ceremony.html'),
(5, 'Command', 1, 'Enchantment', 'hechizo_command.html'),
(5, 'Compelled Duel', 1, 'Enchantment', 'hechizo_compelled_duel.html'),
(5, 'Cure Wounds', 1, 'Evocation', 'hechizo_cure_wounds.html'),
(5, 'Detect Evil and Good', 1, 'Divination', 'hechizo_detect_evil_and_good.html'),
(5, 'Detect Magic', 1, 'Divination', 'hechizo_detect_magic.html'),
(5, 'Detect Poison and Disease', 1, 'Divination', 'hechizo_detect_poison_and_disease.html'),
(5, 'Divine Favor', 1, 'Evocation', 'hechizo_divine_favor.html'),
(5, 'Heroism', 1, 'Enchantment', 'hechizo_heroism.html'),
(5, 'Protection from Evil and Good', 1, 'Abjuration', 'hechizo_protection_from_evil_and_good.html'),
(5, 'Purify Food and Drink', 1, 'Transmutation', 'hechizo_purify_food_and_drink.html'),
(5, 'Searing Smite', 1, 'Evocation', 'hechizo_searing_smite.html'),
(5, 'Shield of Faith', 1, 'Abjuration', 'hechizo_shield_of_faith.html'),
(5, 'Thunderous Smite', 1, 'Evocation', 'hechizo_thunderous_smite.html'),
(5, 'Wrathful Smite', 1, 'Evocation', 'hechizo_wrathful_smite.html'),
(5, 'Aid', 2, 'Abjuration', 'hechizo_aid.html'),
(5, 'Branding Smite', 2, 'Evocation', 'hechizo_branding_smite.html'),
(5, 'Find Steed', 2, 'Conjuration', 'hechizo_find_steed.html'),
(5, 'Find Vehicle (UA)', 2, 'Conjuration T', 'hechizo_find_vehicle.html'),
(5, 'Gentle Repose', 2, 'Necromancy', 'hechizo_gentle_repose.html'),
(5, 'Lesser Restoration', 2, 'Abjuration', 'hechizo_lesser_restoration.html'),
(5, 'Locate Object', 2, 'Divination', 'hechizo_locate_object.html'),
(5, 'Magic Weapon', 2, 'Transmutation', 'hechizo_magic_weapon.html'),
(5, 'Prayer of Healing', 2, 'Evocation', 'hechizo_prayer_of_healing.html'),
(5, 'Protection from Poison', 2, 'Abjuration', 'hechizo_protection_from_poison.html'),
(5, 'Warding Bond', 2, 'Abjuration', 'hechizo_warding_bond.html'),
(5, 'Zone of Truth', 2, 'Enchantment', 'hechizo_zone_of_truth.html'),
(5, 'Aura of Vitality', 3, 'Evocation', 'hechizo_aura_of_vitality.html'),
(5, 'Blinding Smite', 3, 'Evocation', 'hechizo_blinding_smite.html'),
(5, 'Create Food and Water', 3, 'Conjuration', 'hechizo_create_food_and_water.html'),
(5, 'Crusader''s Mantle', 3, 'Evocation', 'hechizo_crusaders_mantle.html'),
(5, 'Daylight', 3, 'Evocation', 'hechizo_daylight.html'),
(5, 'Dispel Magic', 3, 'Abjuration', 'hechizo_dispel_magic.html'),
(5, 'Elemental Weapon', 3, 'Transmutation', 'hechizo_elemental_weapon.html'),
(5, 'Magic Circle', 3, 'Abjuration', 'hechizo_magic_circle.html'),
(5, 'Remove Curse', 3, 'Abjuration', 'hechizo_remove_curse.html'),
(5, 'Revivify', 3, 'Necromancy', 'hechizo_revivify.html'),
(5, 'Spirit Shroud', 3, 'Necromancy', 'hechizo_spirit_shroud.html'),
(5, 'Aura of Life', 4, 'Abjuration', 'hechizo_aura_of_life.html'),
(5, 'Aura of Purity', 4, 'Abjuration', 'hechizo_aura_of_purity.html'),
(5, 'Banishment', 4, 'Abjuration', 'hechizo_banishment.html'),
(5, 'Death Ward', 4, 'Abjuration', 'hechizo_death_ward.html'),
(5, 'Find Greater Steed', 4, 'Conjuration', 'hechizo_find_greater_steed.html'),
(5, 'Locate Creature', 4, 'Divination', 'hechizo_locate_creature.html'),
(5, 'Staggering Smite', 4, 'Evocation', 'hechizo_staggering_smite.html'),
(5, 'Banishing Smite', 5, 'Abjuration', 'hechizo_banishing_smite.html'),
(5, 'Circle of Power', 5, 'Abjuration', 'hechizo_circle_of_power.html'),
(5, 'Destructive Wave', 5, 'Evocation', 'hechizo_destructive_wave.html'),
(5, 'Dispel Evil and Good', 5, 'Abjuration', 'hechizo_dispel_evil_and_good.html'),
(5, 'Geas', 5, 'Enchantment', 'hechizo_geas.html'),
(5, 'Holy Weapon', 5, 'Evocation', 'hechizo_holy_weapon.html'),
(5, 'Raise Dead', 5, 'Necromancy', 'hechizo_raise_dead.html'),
(5, 'Summon Celestial', 5, 'Conjuration', 'hechizo_summon_celestial.html'),
(6, 'Bendecir', 1, 'Encantamiento', 'hechizo_bendecir.html'),
(6, 'Ceremonia', 1, 'Evocación', 'hechizo_ceremonia.html'),
(6, 'Mandar', 1, 'Encantamiento', 'hechizo_mandar.html'),
(6, 'Duelo obligado', 1, 'Encantamiento', 'hechizo_duelo_obligado.html'),
(6, 'Curar heridas', 1, 'Evocación', 'hechizo_curar_heridas.html'),
(6, 'Detectar el mal y el bien', 1, 'Adivinación', 'hechizo_detectar_mal_bien.html'),
(6, 'Detectar magia', 1, 'Adivinación', 'hechizo_detectar_magia.html'),
(6, 'Detectar venenos y enfermedades', 1, 'Adivinación', 'hechizo_detectar_venenos.html'),
(6, 'Favor Divino', 1, 'Evocación', 'hechizo_favor_divino.html'),
(6, 'Heroísmo', 1, 'Encantamiento', 'hechizo_heroismo.html'),
(6, 'Protección contra el mal y el bien', 1, 'Abjuración', 'hechizo_proteccion_mal_bien.html'),
(6, 'Purificar alimentos y bebidas', 1, 'Transmutación', 'hechizo_purificar_alimentos.html'),
(6, 'Castigo abrasador', 1, 'Evocación', 'hechizo_castigo_abrasador.html'),
(6, 'Escudo de la fe', 1, 'Abjuración', 'hechizo_escudo_fe.html'),
(6, 'Castigo atronador', 1, 'Evocación', 'hechizo_castigo_atronador.html'),
(6, 'Castigo iracundo', 1, 'Evocación', 'hechizo_castigo_iracundo.html');

------>Ranger
